[project]
name = "persistent-mind-model"
version = "0.0.0"
description = "PMM refactor scaffold: persistent, model-agnostic AI mind (skeleton)."
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
  "ruff>=0.5.0",
  "black>=24.0.0",
  "pytest>=7.0.0",
  "pytest-cov>=4.0.0",
  "mypy>=1.4.0",
  "isort>=5.12.0",
  "pre-commit>=3.3.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
