[project]
name = "persistent-mind-model"
version = "0.0.0"
description = "PMM refactor scaffold: persistent, model-agnostic AI mind (skeleton)."
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
